name: taptap
description: Making poking around useful.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fluro: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  # assets/fonts/jokuOmaFontti.ttf
  assets/i18n/en.json
  assets/i18n/fi.json
  # assets/images/jokuKuva.jpg
